// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vipra.Infrastructure;

#nullable disable

namespace Vipra.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Vipra.Domain.Entities.Panditji", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Experience")
                        .HasColumnType("tinyint");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Panditjis");
                });

            modelBuilder.Entity("Vipra.Domain.Entities.PanditjiSpecialization", b =>
                {
                    b.Property<Guid>("PanditjiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SpecializationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PanditjiId", "SpecializationId");

                    b.HasIndex("SpecializationId");

                    b.ToTable("PanditjiSpecializations");
                });

            modelBuilder.Entity("Vipra.Domain.Entities.Specialization", b =>
                {
                    b.Property<Guid>("SpecializationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SpecializationId");

                    b.ToTable("Specializations");
                });

            modelBuilder.Entity("Vipra.Domain.Entities.Yajman", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gotra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Yajmans");
                });

            modelBuilder.Entity("Vipra.Domain.Entities.YajmanPanditji", b =>
                {
                    b.Property<Guid>("PanditjiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("YajmanId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PanditjiId", "YajmanId");

                    b.HasIndex("YajmanId");

                    b.ToTable("YajmanPanditjis");
                });

            modelBuilder.Entity("Vipra.Domain.Entities.PanditjiSpecialization", b =>
                {
                    b.HasOne("Vipra.Domain.Entities.Panditji", "Panditji")
                        .WithMany("PanditjiSpecializations")
                        .HasForeignKey("PanditjiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vipra.Domain.Entities.Specialization", "Specialization")
                        .WithMany("PanditjiSpecializations")
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Panditji");

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("Vipra.Domain.Entities.YajmanPanditji", b =>
                {
                    b.HasOne("Vipra.Domain.Entities.Panditji", "Panditji")
                        .WithMany("YajmanPanditjis")
                        .HasForeignKey("PanditjiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vipra.Domain.Entities.Yajman", "Yajman")
                        .WithMany("YajmanPanditjis")
                        .HasForeignKey("YajmanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Panditji");

                    b.Navigation("Yajman");
                });

            modelBuilder.Entity("Vipra.Domain.Entities.Panditji", b =>
                {
                    b.Navigation("PanditjiSpecializations");

                    b.Navigation("YajmanPanditjis");
                });

            modelBuilder.Entity("Vipra.Domain.Entities.Specialization", b =>
                {
                    b.Navigation("PanditjiSpecializations");
                });

            modelBuilder.Entity("Vipra.Domain.Entities.Yajman", b =>
                {
                    b.Navigation("YajmanPanditjis");
                });
#pragma warning restore 612, 618
        }
    }
}
